export interface LanguageElement {
  readonly number: number;
  readonly category: string;
  readonly name: string;
  readonly syntax: string;
  readonly description: string;
}

export const languageElements: readonly LanguageElement[] = [
  { number: 1, category: 'Basic Types', name: 'Text', syntax: 'text', description: 'UTF-8 string primitive type.' },
  { number: 2, category: 'Basic Types', name: 'Number', syntax: 'num', description: 'Double-precision floating point number type.' },
  { number: 3, category: 'Basic Types', name: 'Boolean', syntax: 'bool', description: 'True or false logic value.' },
  { number: 4, category: 'Basic Types', name: 'List', syntax: 'list<T>', description: 'Dynamically resized ordered container.' },
  { number: 5, category: 'Basic Types', name: 'Dictionary', syntax: 'dict<K, V>', description: 'Typed key-value store.' },
  { number: 6, category: 'Basic Types', name: 'Void', syntax: 'void', description: 'Absence of a return value.' },
  { number: 7, category: 'Basic Types', name: 'Any', syntax: 'any', description: 'Explicit escape hatch from static checking.' },
  { number: 8, category: 'Extended JSON Types', name: 'Date', syntax: 'date', description: 'High-level date and time object.' },
  { number: 9, category: 'Extended JSON Types', name: 'Duration', syntax: 'time', description: 'Exact intervals such as 5s and 100ms.' },
  { number: 10, category: 'Extended JSON Types', name: 'Bytes', syntax: 'bytes', description: 'Raw binary buffers for web and media data.' },
  { number: 11, category: 'Extended JSON Types', name: 'Precise Math', syntax: 'decimal', description: 'String-backed decimal value for exact interchange.' },
  { number: 12, category: 'Extended JSON Types', name: 'Identifier', syntax: 'id', description: 'Built-in UUID v4 identifier.' },
  { number: 13, category: 'Extended JSON Types', name: 'Set', syntax: 'set<T>', description: 'Unordered collection of unique values.' },
  { number: 14, category: 'Extended JSON Types', name: 'Regex', syntax: 'regex', description: 'Pattern literal written as r"pattern".' },
  { number: 15, category: 'OOP & Classes', name: 'Class Keyword', syntax: 'class(Name)', description: 'Declares an object blueprint.' },
  { number: 16, category: 'OOP & Classes', name: 'Self Pointer', syntax: 'self', description: 'Reference to the current object.' },
  { number: 17, category: 'OOP & Classes', name: 'Constructor', syntax: 'create(...)', description: 'Runs when a class is instantiated.' },
  { number: 18, category: 'OOP & Classes', name: 'Inheritance', syntax: 'class(Child:Parent)', description: 'Inherits behavior and state from a parent.' },
  { number: 19, category: 'OOP & Classes', name: 'Instantiation', syntax: 'new(Class, ...)', description: 'Creates an object instance.' },
  { number: 20, category: 'OOP & Classes', name: 'Public Access', syntax: 'pub(member)', description: 'Exposes a member outside its class.' },
  { number: 21, category: 'OOP & Classes', name: 'Private Access', syntax: 'priv(member)', description: 'Restricts a member to its class.' },
  { number: 22, category: 'OOP & Classes', name: 'Parent Access', syntax: 'super', description: 'Calls parent methods or constructors.' },
  { number: 23, category: 'Control Flow', name: 'If Branch', syntax: 'if(condition)', description: 'Runs a block conditionally.' },
  { number: 24, category: 'Control Flow', name: 'Else Branch', syntax: 'else', description: 'Provides an alternative branch.' },
  { number: 25, category: 'Control Flow', name: 'Unified Loop', syntax: 'loop(header)', description: 'Iterates items or repeats while a condition holds.' },
  { number: 26, category: 'Control Flow', name: 'Return', syntax: 'return(value);', description: 'Exits a method with a typed result.' },
  { number: 27, category: 'Control Flow', name: 'Break', syntax: 'break', description: 'Stops the current loop.' },
  { number: 28, category: 'Control Flow', name: 'Continue', syntax: 'continue', description: 'Moves to the next loop iteration.' },
  { number: 29, category: 'Control Flow', name: 'Match', syntax: 'match(value)', description: 'Readable value pattern matching.' },
  { number: 30, category: 'Control Flow', name: 'Try/Catch', syntax: 'try / catch', description: 'Handles runtime exceptions.' },
  { number: 31, category: 'Syntax & Punctuators', name: 'Code Blocks', syntax: '{}', description: 'Curly braces define scopes and structures.' },
  { number: 32, category: 'Syntax & Punctuators', name: 'Expressions', syntax: '()', description: 'Groups expressions and calls functions.' },
  { number: 33, category: 'Syntax & Punctuators', name: 'Indexing', syntax: '[]', description: 'Creates lists and looks up values.' },
  { number: 34, category: 'Syntax & Punctuators', name: 'Terminator', syntax: ';', description: 'Enforces clear statement boundaries.' },
  { number: 35, category: 'Syntax & Punctuators', name: 'Type Colon', syntax: ':', description: 'Associates a declaration with its type.' },
  { number: 36, category: 'Syntax & Punctuators', name: 'Legacy Line Comment', syntax: '// (deprecated)', description: 'Accepted during v0.2 migration; convert to punctuation-delimited block comments.' },
  { number: 37, category: 'Syntax & Punctuators', name: 'Block Comment', syntax: '/* */', description: 'Ignores a multi-line block.' },
  { number: 38, category: 'Syntax & Punctuators', name: 'Null Safety', syntax: '?', description: 'Marks a type as nullable.' },
  { number: 39, category: 'Standard Library', name: 'Output', syntax: 'print()', description: 'Writes values to the output panel.' },
  { number: 40, category: 'Standard Library', name: 'Input', syntax: 'input()', description: 'Requests interactive input.' },
  { number: 41, category: 'Standard Library', name: 'Length', syntax: 'len()', description: 'Counts text, collection, or dictionary items.' },
  { number: 42, category: 'Standard Library', name: 'Range Generator', syntax: 'range()', description: 'Creates a number sequence.' },
  { number: 43, category: 'Standard Library', name: 'String Cast', syntax: 'str()', description: 'Converts a value to text.' },
  { number: 44, category: 'Standard Library', name: 'Number Cast', syntax: 'num()', description: 'Safely parses a numeric value.' },
  { number: 45, category: 'Standard Library', name: 'JSON Serialize', syntax: 'toJSON()', description: 'Serializes data to JSON text.' },
  { number: 46, category: 'Standard Library', name: 'JSON Deserialize', syntax: 'parseJSON()', description: 'Parses JSON text into data.' },
  { number: 47, category: 'Standard Library', name: 'Delay', syntax: 'wait()', description: 'Pauses asynchronously for a duration.' },
  { number: 48, category: 'Standard Library', name: 'HTTP Fetch', syntax: 'web.fetch()', description: 'Makes asynchronous web requests.' },
  { number: 49, category: 'Standard Library', name: 'Random', syntax: 'math.random()', description: 'Returns a number from zero through one.' },
  { number: 50, category: 'Standard Library', name: 'Type Inspector', syntax: 'typeOf()', description: 'Returns the runtime type name.' },
];
